### ISSUE TITLE
Support for package.json references

### ISSUE THREAD

**Issue by Askelkana** [jtrussell/svn-npm-crutch#4]
For example:

    "svn": {
      "repoX": "https://repoX.com/"
    }
    "svnDependencies": {
      "moduleX": "<%= pkg.svn.repoX %>/moduleX/trunk"
    }

doesn't work, but should (or at least would be nice if it did).

**Comment by jtrussell** [comment]
Is this something npm does? I've never used it myself and didn't see any reference to the behavior with a quick search through the docs.

**Comment by Askelkana** [comment]
You're right. It's something that grunt does. I've hardly used node without grunt, so the feature (which is very handy) has grown on me to the point that it's become ubiquitous.

I'll close this, and get me coat.
